
package com.example.ws.premier;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PremierService", targetNamespace = "http://www.example.com/ws/Premier")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PremierService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "metAJourHistorique", targetNamespace = "http://www.example.com/ws/Premier", className = "com.example.ws.premier.MetAJourHistorique")
    @ResponseWrapper(localName = "metAJourHistoriqueResponse", targetNamespace = "http://www.example.com/ws/Premier", className = "com.example.ws.premier.MetAJourHistoriqueResponse")
    public String metAJourHistorique(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
