
package com.example.ws.premier;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PremierService", targetNamespace = "http://www.example.com/ws/Premier", wsdlLocation = "http://localhost:8080/PremierService?wsdl")
public class PremierService_Service
    extends Service
{

    private final static URL PREMIERSERVICE_WSDL_LOCATION;
    private final static WebServiceException PREMIERSERVICE_EXCEPTION;
    private final static QName PREMIERSERVICE_QNAME = new QName("http://www.example.com/ws/Premier", "PremierService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/PremierService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PREMIERSERVICE_WSDL_LOCATION = url;
        PREMIERSERVICE_EXCEPTION = e;
    }

    public PremierService_Service() {
        super(__getWsdlLocation(), PREMIERSERVICE_QNAME);
    }

    public PremierService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PREMIERSERVICE_QNAME, features);
    }

    public PremierService_Service(URL wsdlLocation) {
        super(wsdlLocation, PREMIERSERVICE_QNAME);
    }

    public PremierService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PREMIERSERVICE_QNAME, features);
    }

    public PremierService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PremierService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PremierService
     */
    @WebEndpoint(name = "Premier")
    public PremierService getPremier() {
        return super.getPort(new QName("http://www.example.com/ws/Premier", "Premier"), PremierService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PremierService
     */
    @WebEndpoint(name = "Premier")
    public PremierService getPremier(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.com/ws/Premier", "Premier"), PremierService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PREMIERSERVICE_EXCEPTION!= null) {
            throw PREMIERSERVICE_EXCEPTION;
        }
        return PREMIERSERVICE_WSDL_LOCATION;
    }

}
