
package com.example.ws.second;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SecondService", targetNamespace = "http://www.example.com/ws/Second", wsdlLocation = "http://localhost:8080/SecondService?wsdl")
public class SecondService_Service
    extends Service
{

    private final static URL SECONDSERVICE_WSDL_LOCATION;
    private final static WebServiceException SECONDSERVICE_EXCEPTION;
    private final static QName SECONDSERVICE_QNAME = new QName("http://www.example.com/ws/Second", "SecondService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SecondService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SECONDSERVICE_WSDL_LOCATION = url;
        SECONDSERVICE_EXCEPTION = e;
    }

    public SecondService_Service() {
        super(__getWsdlLocation(), SECONDSERVICE_QNAME);
    }

    public SecondService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SECONDSERVICE_QNAME, features);
    }

    public SecondService_Service(URL wsdlLocation) {
        super(wsdlLocation, SECONDSERVICE_QNAME);
    }

    public SecondService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SECONDSERVICE_QNAME, features);
    }

    public SecondService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecondService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SecondService
     */
    @WebEndpoint(name = "Second")
    public SecondService getSecond() {
        return super.getPort(new QName("http://www.example.com/ws/Second", "Second"), SecondService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecondService
     */
    @WebEndpoint(name = "Second")
    public SecondService getSecond(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.com/ws/Second", "Second"), SecondService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SECONDSERVICE_EXCEPTION!= null) {
            throw SECONDSERVICE_EXCEPTION;
        }
        return SECONDSERVICE_WSDL_LOCATION;
    }

}
