
package com.example.ws.second;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SecondService", targetNamespace = "http://www.example.com/ws/Second")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SecondService {


    /**
     * 
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "size", targetNamespace = "http://www.example.com/ws/Second", className = "com.example.ws.second.Size")
    @ResponseWrapper(localName = "sizeResponse", targetNamespace = "http://www.example.com/ws/Second", className = "com.example.ws.second.SizeResponse")
    public Integer size();

}
